### ISSUE TITLE
Generalized swerve drive train system

### ISSUE THREAD

**Issue by SoZ0** [FRC-6390/Crecendo-2024#3]
**NOTE**: #2 Must be completed before this can be completed

# The problem

Our current drive train is too specific and is not easily extensible. We need to make it more generalizable for future use and to allow easier debugging and testing.

## Vision

A drive train system specialized for Swerve drive train systems only. This system should **ONLY** provide information and tools directly related to the systems used in the drive train. This will directly exclude and vision or localization systems, these systems have outgrown the drive train and now require their own place with in the code base.

File: ```SwerveDriveTrain.java```

Location: ```src/main/java/frc/robot/utils/drivetrain```

**NOTE:** Do not make this a subsystem! We will be moving away from WPILib to avoid the need for updating and maintaining based off of WPILib. Only specific implamentation for a specific robot will instead import the new system being created and fill in the required needs.

---

# Variables

- [ ] **SwerveDriveKinematics kinematics**
- [ ] **Pigeon2 gyro**
- [ ] **SwerveModule[] modules**
- [ ] **BooleanSupplier driftCorrection**
- [ ] **PID driftCorrectionConfig**
- [ ] **ChassisSpeeds driveSpeeds, addedSpeeds**

# Methods

## Constructor ```SwerveModule[] modules, Pigeon2 gyro```,
call the constructor overload that takes in ```SwerveModule[], Pigeon2, boolean```
the defualt value for ```boolean``` is false

## Constructor ```SwerveModule[] modules, Pigeon2 gyro, boolean driftCorrection, PIDConfig driftCorrectionConfig```,
call the constructor overload that takes in ```SwerveModule[], Pigeon2, BooleanSupplier, PIDConfig```

## Constructor ```SwerveModule[] modules, Pigeon2 gyro, BooleanSupplier driftCorrection, PIDConfig driftCorrectionConfig```,
all variables should initilized inside the constructor. populating the following variables is required.

- [x]  **SwerveModule[] modules**
- [x]  **Pigeon2 gyro**
- [x]  **SwerveDriveKinematics kinematics**
- [ ]  **BooleanSupplier driftCorrection**
- [x]  **PID driftCorrectionConfig**
- [x] **ChassisSpeeds driveSpeeds, addedSpeeds**

# Gyro Methods

## `public DoubleSupplier getYawSupplier()`
will call ```public double getYaw()``` for value

## `public double getYaw()`
returns the yaw value of the gyro

## `public DoubleSupplier getRollSupplier()`
will call ```public double getRoll()``` for value

## public double getRoll()
returns the roll value of the gyro

## `public DoubleSupplier getPitchSupplier()`
will call ```public double getPitch()``` for value

## `public double getPitch()`
returns the pitch value of the gyro

## `public void resetYaw()`
will call ```public void resetYaw(0)```

## `public void resetYaw(double val)`
will set the gyro yaw to the value passed in.

# Swerve Module Methods

## `private void setModuleStates(SwerveModuleState[] states)`
will loop through the modules and set desired states

## `public void lockWheels()`
will call the ```lock()``` method on each module.

## `public void unlockWheels()`
will call the ```unlock()``` method on each module.

# Drive Methods

## `public void drive(ChassisSpeeds driveSpeeds)`
will set driveSpeeds to the passed in value.

## `public void addSpeed(ChassisSpeeds addedSpeeds)`
will set addedSpeeds to the passed in value

## `public void update()`
will run all the operations to update the drive train on the robot
this will add the driveSpeeds to the addedSpeeds and then call the `setModuleStates` method.

## `public void enableDriftCorrection()`
this should set the boolean tracking drift correction to `true` 

## `public void disableDriftCorrection()`
this should set the boolean tracking drift correction to `false` 

## Tasks

- [x] **Constructors**
- [x] **Gyro Methods**
- [x] **Swerve Module Methods**
- [x] **Drive Methods**
- [ ] **Shuffleboard**

**Comment by MahditS** [comment]
DONNEEEEEEEEEEEE
